
////
+++
title = "About"
date = "2023-05-07"
menu = "main"
weight=1000
+++
////

= How to

This site provides help for various situations.

== How to release new version of software (Java)

https://wyssmann.com/blog/2021/03/how-to-increment-versions-in-maven-builds-alternative-to-maven-release-plugin/

=== 1. Ask versions

```
echo What is current snapshot version? example=1.2.3-SNAPSHOT
read currentSnapshotVersion
echo What is current release version? example=1.2.3
read currentReleaseVersion
echo What is next snapshot version? example=1.2.4-SNAPSHOT
read nextSnapshotVersion
echo ""
echo Review:
echo currentSnapshotVersion = $currentSnapshotVersion
echo currentReleaseVersion = $currentReleaseVersion
echo nextSnapshotVersion = $nextSnapshotVersion
```

=== 2. Deploy current snapshot to Maven repository

```
git checkout develop
mvn clean deploy&&echo "DONE"
```

=== 3. Change currentSnapshotVersion to currentReleaseVersion : Delete -SNAPSHOT- all occurences in poms

```
git checkout master
git merge develop
mvn build-helper:parse-version versions:set \
 -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}
mvn versions:commit
```

Additionally you may also have to change the *.version Maven property like: <power.version>2.0.0</power.version>

=== 4. Add the deletion to git

```
git add .&&echo "DONE"
```

=== 5. Commit the released version to git

```
git commit -m "Released $currentReleaseVersion"&&echo "DONE"
```

=== 6. Deploy released version to Maven repository

```
mvn clean deploy&&echo "DONE"
```

=== 7. Tag released version

```
#git tag -d 0.0.0
#git push --delete origin 0.0.0
#git tag -a $currentReleaseVersion -m "$currentReleaseVersion"&&echo "DONE"

git tag v$currentReleaseVersion&&echo "DONE"
```

=== 8. Push to git

```
#git push -f origin HEAD;

git push origin HEAD&&echo "DONE"
```

=== 9. Push new tag to git

```
git push origin v$currentReleaseVersion&&echo "DONE"
```

=== 10. Increase version and add -SNAPSHOST  \(example: 999.999.999-SNAPSHOT\)

```
git checkout develop
git merge master
mvn build-helper:parse-version versions:set \
-DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
mvn versions:commit
```

Additionally you may also have to change the *.version Maven property like: <power.version>2.0.1-SNAPSHOT</power.version>

=== 11. Adding the changes to git

```
git add .&&echo "DONE"
```

=== 12. Commit the new snapshot version to git

```
git commit -m "Released for the first time $nextSnapshotVersion"&&echo "DONE"
```

=== 13. Push to git

```
git push origin HEAD&&echo "DONE"
```

=== 14. Deploy the new snapshot to Maven repository

```
mvn clean deploy&&echo "DONE"
```

=== 15. Now the RELEASE OF NEW VERSION $currentReleaseVersion WAS JUST FINISHED"

