
////
+++
title = "About"
date = "2023-05-07"
menu = "main"
weight=1000
+++
////

= How to

This site provides help for various situations.

== How to release new version of software (Java)

https://wyssmann.com/blog/2021/03/how-to-increment-versions-in-maven-builds-alternative-to-maven-release-plugin/

=== 1. What is current snapshot version?

```
#example:
currentSnapshotVersion=1.2.3-SNAPSHOT
```

=== 2. What is current release version?

```
#example:
currentReleaseVersion=1.2.3
```

=== 3. What is next snapshot version?

```
#example:
nextSnapshotVersion=1.3.0
```

=== 4. Deploy current snapshot to Maven repository

```
git checkout develop
mvn clean deploy&&echo "DONE"
```

=== 5. Change currentSnapshotVersion to currentReleaseVersion : Delete -SNAPSHOT- all occurences in poms

```
git checkout master
git merge develop
mvn build-helper:parse-version versions:set \
 -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}
mvn versions:commit
```

=== 6. Add the deletion to git

```
git add .&&echo "DONE"
```

=== 7. Commit the released version to git

```
git commit -m "Released $currentReleaseVersion"&&echo "DONE"
```

=== 8. Deploy released version to Maven repository

```
mvn clean deploy&&echo "DONE"
```

=== 9. Tag released version

```
#git tag -d 0.0.0
#git push --delete origin 0.0.0

#git tag -a $currentVersion -m "$currentVersion"&&echo "DONE"
git tag $currentReleaseVersion&&echo "DONE"
```

=== 10. Push to git

```
#git push -f origin HEAD;
git push origin HEAD&&echo "DONE"
```

=== 11. Push new tag to git

```
git push origin $currentReleaseVersion&&echo "DONE"
```

=== 12. Increase version and add -SNAPSHOST  \(example: 999.999.999-SNAPSHOT\)

```
git checkout develop
git merge master
mvn build-helper:parse-version versions:set \
-DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
mvn versions:commit
```

=== 13. Adding the changes to git

```
git add .&&echo "DONE"
```

=== 14. Commit the new snapshot version to git

```
git commit -m "Released for the first time" "$nextSnapshotVersion"&&echo "DONE"
```

=== 15. Push to git

```
git push origin HEAD&&echo "DONE"
```

=== 16. Deploy the new snapshot to Maven repository

```
mvn clean deploy&&echo "DONE"
```

=== 17. Now the RELEASE OF NEW VERSION $currentReleaseVersion WAS JUST FINISHED"

