
////
+++
title = "About"
date = "2023-05-07"
menu = "main"
weight=720
+++
////

= Nanoboot projects

This site provides review of "Nanoboot" packages with links to their documentation and their status.

* The goal of this is to give a clearer overview of different responsibilities at Nanoboot.

If you feel like one project is not working the way you want,
either consider joining the team,
or discussing the matter in the (https://forum.nanoboot.org).

Description of fields:

* Status: [active, inactive] + [working, partly limitations, not working] explains if a project is active and making progress or not
* Maintainers: How many (x/y determine that there might not be as many as wanted)? Enough?
* Discussion: links to project communication hubs (mainly chats)
* Limitations: Is there a restriction determining if you can help?
* Stack: Which experiences could come handy?

NOTE: Some of the infrastructure projects require certain access levels to Nanoboot's infrastructure.

List of packages is here: https://cloud.nanoboot.org/?view_file_with_id=5beebc1b-d338-45e0-a3db-7468a3806a98[Package]

